### ISSUE TITLE
 Incorrect string value: '\xCF\x89-3 P...' for column 'name' when importing Reactome Pathways

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/rdp#295]
```
java.sql.SQLException: Incorrect string value: '\xCF\x89-3 P...' for column 'name' at row 1         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.29.jar!/:8.0.29]         at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.29.jar!/:8.0.29]         at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-java-8.0.29.jar!/:8.0.29]         at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-java-8.0.29.jar!/:8.0.29]         at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.29.jar!/:8.0.29]         at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-connector-java-8.0.29.jar!/:8.0.29]         at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994) ~[mysql-connector-java-8.0.29.jar!/:8.0.29]         at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar!/:na]
```

**Comment by arteymix** [comment]
This could be due to an invalid character in Reactome file, I'll investigate...

**Comment by arteymix** [comment]
This was actually caused by a misconfiguration of the database character set. All fixed!
