### ISSUE TITLE
NullPointerExcpetion when loading MONDO

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/rdp#416]
```
Aug 05 09:14:23 D-fgRegister-03v java[61970]: java.lang.NullPointerException: null
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at ubc.pavlab.rdp.services.OntologyService.saveFromObo(OntologyService.java:297) ~[classes!/:1.5.8]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at ubc.pavlab.rdp.services.OntologyService.updateFromObo(OntologyService.java:278) ~[classes!/:1.5.8]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at ubc.pavlab.rdp.services.OntologyService.updateOntologies(OntologyService.java:519) ~[classes!/:1.5.8]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at ubc.pavlab.rdp.services.OntologyService$$FastClassBySpringCGLIB$$9a009314.invoke(<generated>) ~[classes!/:1.5.8]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at ubc.pavlab.rdp.services.OntologyService$$EnhancerBySpringCGLIB$$f91a621.updateOntologies(<generated>) ~[classes!/:1.5.8]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at ubc.pavlab.rdp.services.CacheService.updateCache(CacheService.java:67) ~[classes!/:1.5.8]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_412]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_412]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_412]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_412]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.27.jar!/:5.3.27]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114) ~[spring-boot-2.6.15.jar!/:2.6.15]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82) ~[spring-boot-2.6.15.jar!/:2.6.15]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_412]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.6.15.jar!/:2.6.15]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.6.15.jar!/:2.6.15]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82) ~[spring-boot-2.6.15.jar!/:2.6.15]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.6.15.jar!/:2.6.15]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) [spring-boot-2.6.15.jar!/:2.6.15]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-2.6.15.jar!/:2.6.15]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at ubc.pavlab.rdp.Application.main(Application.java:17) [classes!/:1.5.8]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_412]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_412]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_412]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_412]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [rdp-1.5.8.jar:1.5.8]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [rdp-1.5.8.jar:1.5.8]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [rdp-1.5.8.jar:1.5.8]
Aug 05 09:14:23 D-fgRegister-03v java[61970]: at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [rdp-1.5.8.jar:1.5.8]
```

**Comment by arteymix** [comment]
According to the code, it looks like the name of the term wasn't filled.
